### ISSUE TITLE
no such file or directory, scandir '/usr/local/lib/node_modules/wepy-cli/node_modules/node-sass/vendor'

### ISSUE THREAD

**Issue by leehave** [wepyjs/wepy-wechat-demo#1]
return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/wepy-cli/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at Object.getInstalledBinaries (/usr/local/lib/node_modules/wepy-cli/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/usr/local/lib/node_modules/wepy-cli/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/local/lib/node_modules/wepy-cli/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/local/lib/node_modules/wepy-cli/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/local/lib/node_modules/wepy-cli/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/wepy-cli/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

**Comment by Gcaufy** [comment]
wepy-cli安装失败是么？

重装试试：
```
npm install -g wepy-cli
```

**Comment by Gcaufy** [comment]
刚测试了一下，在 `win7`, `node v6.0.0` , `wepy v1.13`下测试通过。

**Comment by leehave** [comment]
OSX node v6.2.0 wepy失败

**Comment by Gcaufy** [comment]
还好用么？手动安装sass试试呢？
`npm install node-sass -g`
