### ISSUE TITLE
尝试编译2.0分支碰到的问题

### ISSUE THREAD

**Issue by huixisheng** [wepyjs/wepy-wechat-demo#24]
## 尝试1: 
```
git clone 
npm install 
wepy build 
```
wepy-cli版本 1.7.3

报错如下: 
```
/Users/huixisheng/WorkspacesLab/wepy-wechat-demo/src/app.wpy
  38:16  error  Missing space before value for key 'globalData'  key-spacing

✖ 1 problem (1 error, 0 warnings)

/usr/local/lib/node_modules/wepy-cli/lib/compile-wpy.js:478
            var mainPages = wpy.config.pages.map(function (v) {
                                             ^

TypeError: Cannot read property 'map' of undefined
    at Object.compile (/usr/local/lib/node_modules/wepy-cli/lib/compile-wpy.js:478:46)
```

## 尝试2: 
```
https://github.com/Tencent/wepy/tree/2.0.x/packages/cli
npm link 
命令修改为wepy2
```

➜  wepy-wechat-demo git:(2.0) ✗ wepy2 build
```
[15:47:58] ERR! init Make sure module "@wepy/compiler-sass" is installed. If not please try "npm install @wepy/compiler-sass --save-dev".
[15:47:58] ERR! init Can't resolve '@wepy/compiler-sass' in '/Users/huixisheng/WorkspacesLab/wepy-wechat-demo'
[15:47:58] ERR! init Make sure module "@wepy/compiler-babel" is installed. If not please try "npm install @wepy/compiler-babel --save-dev".
[15:47:58] ERR! init Can't resolve '@wepy/compiler-babel' in '/Users/huixisheng/WorkspacesLab/wepy-wechat-demo'
[15:47:58] ERR! init Initialize failed
```
`@wepy/compiler-sass`包没有发布，手动安装。建议官方发布下

```
[15:49:43] ERR! babel Message:
[15:49:43] ERR! babel   Plugin/Preset files are not allowed to export objects, only functions. In /Users/huixisheng/WorkspacesLab/wepy-wechat-demo/node_modules/babel-preset-es2015/lib/index.js
[15:49:43] ERR! babel File:
[15:49:43] ERR! babel   /Users/huixisheng/WorkspacesLab/wepy-wechat-demo/src/app.wpy
[15:49:43] ERR! Plugin/Preset files are not allowed to export objects, only functions. In /Users/huixisheng/WorkspacesLab/wepy-wechat-demo/node_modules/babel-preset-es2015/lib/index.js
[15:49:43] ERR! compile Compile failed. Add "--log trace" to see more details
```
修改
```
    babel: {
      sourceMap: true,
      presets: [
        "@babel/preset-env",
        // "es2015",
        // "stage-1"
      ],
```

```
[15:51:34] ERR! Can't resolve '@wepy/use-promisify' in '/Users/huixisheng/WorkspacesLab/wepy-wechat-demo/src'
[15:51:34] ERR! compile Compile failed. Add "--log trace" to see more details
```
手动安装 `@wepy/use-promisify`

```
[15:52:58] info vendor building vendor
[15:52:58] ERR! TypeError: Cannot read property 'forEach' of undefined
[15:52:58] ERR!     at Compile.scriptDepFix (/Users/huixisheng/WorkspacesLab/wepy/packages/cli/core/plugins/scriptDepFix.js:7:24)
[15:52:58] ERR!     at forEach (/Users/huixisheng/WorkspacesLab/wepy/packages/cli/core/hook.js:34:20)
[15:52:58] ERR!     at Array.forEach (<anonymous>)
[15:52:58] ERR!     at Compile.hookSeq 
...
(/Users/huixisheng/WorkspacesLab/wepy/packages/cli/core/compile.js:243:29)\n    at <anonymous>' }
[15:52:58] ERR! compile Compile failed.
```
添加判断
```
    if (Array.isArray(parsed.parser.deps)) {
      parsed.parser.deps.forEach((dep, i) => {
```
编译通过，预览有报错

![image](https://user-images.githubusercontent.com/1518967/46937229-4d45f380-d093-11e8-898c-66aa33778739.png)

**Comment by amoydavid** [comment]
@dlhandsome 能拉我进群体验2.0？

**Comment by amoydavid** [comment]
@dlhandsome 能拉我进2.0群吗？

**Comment by liuyanming9551** [comment]
现在例子运行不起来了吗？
![image](https://user-images.githubusercontent.com/23226540/47495419-b0e7d200-d886-11e8-9aef-5ddec487c1e4.png)

**Comment by zwyao** [comment]
这个问题，如何解决呢？

**Comment by linengier** [comment]
这个问题，有解决方案吗？我也碰到了这个问题，在线等，比较着急

**Comment by Gcaufy** [comment]
@linengier 具体哪个问题？这是 18 年的 issue 了，先关闭此 issue。建议重开 issue 重新说明。
